name: C/C++ CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  ubuntu:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: setup
      run: sudo apt-get update && sudo apt-get -f install socat cppcheck clang-format-20
    - name: build
      run: make
    - name: test
      run: CLANG_FORMAT=clang-format-20 make check test
    - name: Publish Test Results
      uses: EnricoMi/publish-unit-test-result-action@v2
      with:
        files: test-results.xml
  windows:
    runs-on: windows-latest
    steps:
    - uses: actions/checkout@v2
    - name: build
      shell: cmd
      run: |
        call "C:\Program Files\Microsoft Visual Studio\2022\Enterprise\VC\Auxiliary\Build\vcvars64.bat"
        make CC=cl simple_uart.o
  macos:
    runs-on: macos-latest
    steps:
    - uses: actions/checkout@v2
    - name: build
      run: make