name: C/C++ CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ${{ matrix.os }}

    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]

    steps:
    - uses: actions/checkout@v2
    - name: Setup Ubuntu
      if: startsWith(matrix.os, 'ubuntu')
      run: sudo apt-get update && sudo apt-get -f install socat cppcheck
    - name: build
      run: make
    - name: test
      if: startsWith(matrix.os, 'ubuntu')
      run: make check test
